"""Add pitch to class user

Revision ID: d8ab350e69d6
Revises: 523faa992036
Create Date: 2020-10-25 21:45:38.110189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ab350e69d6'
down_revision = '523faa992036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('author', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_author'), 'users', ['author'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_author'), table_name='users')
    op.drop_column('users', 'author')
    # ### end Alembic commands ###
